@file:Suppress("PackageName")

package ee.ria.DigiDoc.network.sid.dto.response

@Suppress("unused")
enum class SessionStatusResponseProcessStatus {
    OK,
    TIMEOUT,
    USER_REFUSED,
    DOCUMENT_UNUSABLE,
    WRONG_VC,

    REQUIRED_INTERACTION_NOT_SUPPORTED_BY_APP,
    USER_REFUSED_DISPLAYTEXTANDPIN,
    USER_REFUSED_VC_CHOICE,
    USER_REFUSED_CONFIRMATIONMESSAGE,
    USER_REFUSED_CONFIRMATIONMESSAGE_WITH_VC_CHOICE,
    USER_REFUSED_CERT_CHOICE,
    ACCOUNT_NOT_FOUND,
    SESSION_NOT_FOUND,
    MISSING_SESSIONID,
    EXCEEDED_UNSUCCESSFUL_REQUESTS,
    TOO_MANY_REQUESTS,
    NOT_QUALIFIED,
    INVALID_ACCESS_RIGHTS,
    OCSP_INVALID_TIME_SLOT,
    CERTIFICATE_REVOKED,
    OLD_API,
    UNDER_MAINTENANCE,
    GENERAL_ERROR,
    NO_RESPONSE,
    INVALID_SSL_HANDSHAKE,
    TECHNICAL_ERROR,
}
